### ISSUE TITLE
Incorrect value for SpiralPitchFactor

### ISSUE THREAD

**Issue by lukaszkieronski** [HicServices/BadMedicine.Dicom#107]
https://github.com/HicServices/BadMedicine.Dicom/blob/9ee32ebc7a6390031d6c486f12c5a12f64d8f312/BadMedicine.Dicom/DicomDataGenerator.cs#L284

Value "0.0" causes runtime exception, changing it to "0" fixes problem.

**Comment by lukaszkieronski** [comment]
### ds.AddOrUpdate(DicomTag.SpiralPitchFactor, "0.0")
```
02.06.2022 09:00:51 Starting file generation (to c:\tmp)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Double.Parse(String s)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FellowOakDicom.DicomDataset.DoAdd[T](DicomVR vr, DicomTag tag, IList`1 values, Boolean allowUpdate)
   at FellowOakDicom.DicomDataset.DoAdd[T](DicomTag tag, IList`1 values, Boolean allowUpdate)
   at FellowOakDicom.DicomDataset.AddOrUpdate[T](DicomTag tag, T[] values)
   at BadMedicine.Dicom.DicomDataGenerator.GenerateTestDataset(Person p, Series series) in S:\baddicom\BadMedicine.Dicom\BadMedicine.Dicom\DicomDataGenerator.cs:line 284
   at BadMedicine.Dicom.Series..ctor(Study study, Person person, String modality, String imageType, Int32 imageCount, DescBodyPart part) in S:\baddicom\BadMedicine.Dicom\BadMedicine.Dicom\Series.cs:line 109
   at BadMedicine.Dicom.Study..ctor(DicomDataGenerator parent, Person person, ModalityStats modalityStats, Random r) in S:\baddicom\BadMedicine.Dicom\BadMedicine.Dicom\Study.cs:line 122
   at BadMedicine.Dicom.DicomDataGenerator.GenerateStudyImages(Person p, Study& study) in S:\baddicom\BadMedicine.Dicom\BadMedicine.Dicom\DicomDataGenerator.cs:line 188
   at BadMedicine.Dicom.DicomDataGenerator.GenerateTestDataRow(Person p) in S:\baddicom\BadMedicine.Dicom\BadMedicine.Dicom\DicomDataGenerator.cs:line 132
   at BadMedicine.Datasets.DataGenerator.GenerateTestDataFile(IPersonCollection cohort, FileInfo target, Int32 numberOfRecords)
   at BadDicom.Program.RunOptionsAndReturnExitCode(ProgramOptions opts) in S:\baddicom\BadMedicine.Dicom\BadDicom\Program.cs:line 101
```
### ds.AddOrUpdate(DicomTag.SpiralPitchFactor, "0"); 
```
02.06.2022 08:51:23 Starting file generation (to c:\tmp)
02.06.2022 08:51:36 Finished
```

**Comment by tznind** [comment]
Thank for reporting this! Strange that I have not seen this, maybe I have validation disabled or it was only thrown by fo-dicom with a recent dependency bump.

I have updated `develop` and will push a new release asap.
