### ISSUE TITLE
Assembly loading error with latest Releases for windows

### ISSUE THREAD

**Issue by tznind** [HicServices/BadMedicine.Dicom#59]
Downloading, unzipping (into Downloads) and running gives the following:
```
PS C:\Users\UKGC\Downloads\win-x64> ./BadDicom.exe --help
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Threading, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Console.get_IsOutputRedirected()
   at CommandLine.ParserSettings.GetWindowWidth()
   at CommandLine.ParserSettings..ctor()
   at CommandLine.Parser.<>c.<.cctor>b__20_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at CommandLine.Parser.get_Default()
   at BadDicom.Program.Main(String[] args)

```

**Comment by tznind** [comment]
Fixed in https://github.com/HicServices/BadMedicine.Dicom/releases/tag/v0.0.10
